#!/usr/bin/env bash
set -e
VOICES_DIR="D:/tee/work/code/ai interview assist/piper/voices"
BASE="https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en"

dl() {
  local dest="$VOICES_DIR/$1"
  if [ -f "$dest" ] && [ -s "$dest" ]; then echo "skip $1"; return; fi
  echo "get  $1"
  curl -sL --fail -o "$dest" "$2" || echo "FAIL $1"
}

# en_US
dl en_US-amy-low.onnx           "$BASE/en_US/amy/low/en_US-amy-low.onnx"
dl en_US-amy-low.onnx.json      "$BASE/en_US/amy/low/en_US-amy-low.onnx.json"
dl en_US-amy-medium.onnx        "$BASE/en_US/amy/medium/en_US-amy-medium.onnx"
dl en_US-amy-medium.onnx.json   "$BASE/en_US/amy/medium/en_US-amy-medium.onnx.json"
dl en_US-arctic-medium.onnx     "$BASE/en_US/arctic/medium/en_US-arctic-medium.onnx"
dl en_US-arctic-medium.onnx.json "$BASE/en_US/arctic/medium/en_US-arctic-medium.onnx.json"
dl en_US-bryce-medium.onnx      "$BASE/en_US/bryce/medium/en_US-bryce-medium.onnx"
dl en_US-bryce-medium.onnx.json "$BASE/en_US/bryce/medium/en_US-bryce-medium.onnx.json"
dl en_US-danny-low.onnx         "$BASE/en_US/danny/low/en_US-danny-low.onnx"
dl en_US-danny-low.onnx.json    "$BASE/en_US/danny/low/en_US-danny-low.onnx.json"
dl en_US-hfc_female-medium.onnx      "$BASE/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx"
dl en_US-hfc_female-medium.onnx.json "$BASE/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx.json"
dl en_US-hfc_male-medium.onnx        "$BASE/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx"
dl en_US-hfc_male-medium.onnx.json   "$BASE/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json"
dl en_US-joe-medium.onnx        "$BASE/en_US/joe/medium/en_US-joe-medium.onnx"
dl en_US-joe-medium.onnx.json   "$BASE/en_US/joe/medium/en_US-joe-medium.onnx.json"
dl en_US-john-medium.onnx       "$BASE/en_US/john/medium/en_US-john-medium.onnx"
dl en_US-john-medium.onnx.json  "$BASE/en_US/john/medium/en_US-john-medium.onnx.json"
dl en_US-kathleen-low.onnx      "$BASE/en_US/kathleen/low/en_US-kathleen-low.onnx"
dl en_US-kathleen-low.onnx.json "$BASE/en_US/kathleen/low/en_US-kathleen-low.onnx.json"
dl en_US-kristin-medium.onnx    "$BASE/en_US/kristin/medium/en_US-kristin-medium.onnx"
dl en_US-kristin-medium.onnx.json "$BASE/en_US/kristin/medium/en_US-kristin-medium.onnx.json"
dl en_US-kusal-medium.onnx      "$BASE/en_US/kusal/medium/en_US-kusal-medium.onnx"
dl en_US-kusal-medium.onnx.json "$BASE/en_US/kusal/medium/en_US-kusal-medium.onnx.json"
dl en_US-l2arctic-medium.onnx   "$BASE/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx"
dl en_US-l2arctic-medium.onnx.json "$BASE/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx.json"
dl en_US-lessac-low.onnx        "$BASE/en_US/lessac/low/en_US-lessac-low.onnx"
dl en_US-lessac-low.onnx.json   "$BASE/en_US/lessac/low/en_US-lessac-low.onnx.json"
dl en_US-lessac-high.onnx       "$BASE/en_US/lessac/high/en_US-lessac-high.onnx"
dl en_US-lessac-high.onnx.json  "$BASE/en_US/lessac/high/en_US-lessac-high.onnx.json"
dl en_US-libritts-high.onnx     "$BASE/en_US/libritts/high/en_US-libritts-high.onnx"
dl en_US-libritts-high.onnx.json "$BASE/en_US/libritts/high/en_US-libritts-high.onnx.json"
dl en_US-libritts_r-medium.onnx      "$BASE/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx"
dl en_US-libritts_r-medium.onnx.json "$BASE/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json"
dl en_US-ljspeech-medium.onnx   "$BASE/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx"
dl en_US-ljspeech-medium.onnx.json "$BASE/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx.json"
dl en_US-ljspeech-high.onnx     "$BASE/en_US/ljspeech/high/en_US-ljspeech-high.onnx"
dl en_US-ljspeech-high.onnx.json "$BASE/en_US/ljspeech/high/en_US-ljspeech-high.onnx.json"
dl en_US-norman-medium.onnx     "$BASE/en_US/norman/medium/en_US-norman-medium.onnx"
dl en_US-norman-medium.onnx.json "$BASE/en_US/norman/medium/en_US-norman-medium.onnx.json"
dl en_US-ryan-low.onnx          "$BASE/en_US/ryan/low/en_US-ryan-low.onnx"
dl en_US-ryan-low.onnx.json     "$BASE/en_US/ryan/low/en_US-ryan-low.onnx.json"
dl en_US-ryan-medium.onnx       "$BASE/en_US/ryan/medium/en_US-ryan-medium.onnx"
dl en_US-ryan-medium.onnx.json  "$BASE/en_US/ryan/medium/en_US-ryan-medium.onnx.json"
dl en_US-ryan-high.onnx         "$BASE/en_US/ryan/high/en_US-ryan-high.onnx"
dl en_US-ryan-high.onnx.json    "$BASE/en_US/ryan/high/en_US-ryan-high.onnx.json"

# en_GB
dl en_GB-alan-low.onnx           "$BASE/en_GB/alan/low/en_GB-alan-low.onnx"
dl en_GB-alan-low.onnx.json      "$BASE/en_GB/alan/low/en_GB-alan-low.onnx.json"
dl en_GB-alan-medium.onnx        "$BASE/en_GB/alan/medium/en_GB-alan-medium.onnx"
dl en_GB-alan-medium.onnx.json   "$BASE/en_GB/alan/medium/en_GB-alan-medium.onnx.json"
dl en_GB-alba-medium.onnx        "$BASE/en_GB/alba/medium/en_GB-alba-medium.onnx"
dl en_GB-alba-medium.onnx.json   "$BASE/en_GB/alba/medium/en_GB-alba-medium.onnx.json"
dl en_GB-aru-medium.onnx         "$BASE/en_GB/aru/medium/en_GB-aru-medium.onnx"
dl en_GB-aru-medium.onnx.json    "$BASE/en_GB/aru/medium/en_GB-aru-medium.onnx.json"
dl en_GB-cori-medium.onnx        "$BASE/en_GB/cori/medium/en_GB-cori-medium.onnx"
dl en_GB-cori-medium.onnx.json   "$BASE/en_GB/cori/medium/en_GB-cori-medium.onnx.json"
dl en_GB-cori-high.onnx          "$BASE/en_GB/cori/high/en_GB-cori-high.onnx"
dl en_GB-cori-high.onnx.json     "$BASE/en_GB/cori/high/en_GB-cori-high.onnx.json"
dl en_GB-jenny_dioco-medium.onnx      "$BASE/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx"
dl en_GB-jenny_dioco-medium.onnx.json "$BASE/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json"
dl en_GB-northern_english_male-medium.onnx      "$BASE/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx"
dl en_GB-northern_english_male-medium.onnx.json "$BASE/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json"
dl en_GB-semaine-medium.onnx     "$BASE/en_GB/semaine/medium/en_GB-semaine-medium.onnx"
dl en_GB-semaine-medium.onnx.json "$BASE/en_GB/semaine/medium/en_GB-semaine-medium.onnx.json"
dl en_GB-southern_english_female-low.onnx      "$BASE/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx"
dl en_GB-southern_english_female-low.onnx.json "$BASE/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx.json"
dl en_GB-vctk-medium.onnx        "$BASE/en_GB/vctk/medium/en_GB-vctk-medium.onnx"
dl en_GB-vctk-medium.onnx.json   "$BASE/en_GB/vctk/medium/en_GB-vctk-medium.onnx.json"

echo "All done"
