<script lang="ts">
  export interface ReviewSummary {
    id: string;
    created_at: number;
    duration_secs: number;
    source_filename: string;
    source_type: string;
    qa_count: number;
    avg_wpm: number;
    you_pct: number;
  }

  export interface ReviewReport {
    id: string;
    created_at: number;
    duration_secs: number;
    source_filename: string;
    source_type: string;
    transcript: ReviewSegment[];
    qa_pairs: QaPair[];
    vocal_summary: { avg_wpm: number; total_answers: number };
    speaker_summary: { you_pct: number; them_pct: number; you_word_count: number; them_word_count: number; turn_count: number };
    keywords_mentioned: string[];
  }

  interface ReviewSegment {
    speaker: string;
    text: string;
    start_ms: number;
    end_ms: number;
  }

  interface QaPair {
    question: string;
    answer_text: string;
    coaching: string;
    missed_followup: boolean;
    missed_metric: boolean;
    wpm: number;
    duration_secs: number;
    start_ms: number;
  }

  const { report, onClose, onDelete } = $props<{
    report: ReviewReport;
    onClose: () => void;
    onDelete?: (id: string) => void;
  }>();

  let mediaEl = $state<HTMLVideoElement | HTMLAudioElement | null>(null);
  let currentMs = $state(0);
  let expandedQa = $state<number | null>(null);
  let qaListEl = $state<HTMLDivElement | null>(null);
  let prevVisibleCount = $state(0);
  let copyState = $state<'idle' | 'copied'>('idle');
  let emailTo = $state(localStorage.getItem('review-email') ?? '');
  let emailSent = $state(false);
  let confirmDelete = $state(false);

  const isVideo = $derived(['mp4','webm','mov','mkv','avi'].some(
    ext => report.source_filename.toLowerCase().endsWith(`.${ext}`)
  ));

  const sourceUrl = $derived(`/api/review/${report.id}/source`);
  const downloadUrl = $derived(`/api/review/${report.id}/download`);

  function fmtDuration(secs: number): string {
    const m = Math.floor(secs / 60);
    const s = Math.floor(secs % 60);
    return `${m}:${s.toString().padStart(2, '0')}`;
  }

  function fmtDate(unixMs: number): string {
    return new Date(unixMs).toLocaleString(undefined, {
      month: 'short', day: 'numeric', year: 'numeric',
      hour: 'numeric', minute: '2-digit',
    });
  }

  function fmtWpm(wpm: number): string {
    if (wpm < 100) return 'slow';
    if (wpm > 180) return 'fast';
    return 'good';
  }

  function wpmColor(wpm: number): string {
    if (wpm < 100) return '#f59e0b';
    if (wpm > 180) return '#f87171';
    return '#4ade80';
  }

  // Progressive Q&A reveal — cards appear as video reaches their timestamp
  const visibleQa = $derived(
    currentMs > 0
      ? report.qa_pairs.filter(qa => currentMs >= qa.start_ms)
      : report.qa_pairs
  );

  // Auto-scroll to newly revealed card
  $effect(() => {
    const count = visibleQa.length;
    if (currentMs > 0 && count > prevVisibleCount && qaListEl) {
      const cards = qaListEl.querySelectorAll('.qa-item');
      cards[count - 1]?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    prevVisibleCount = count;
  });

  // Highlight transcript segment that matches current playback position
  const activeSegIdx = $derived(() => {
    const ms = currentMs;
    for (let i = report.transcript.length - 1; i >= 0; i--) {
      if (report.transcript[i].start_ms <= ms) return i;
    }
    return -1;
  });

  function seekTo(ms: number) {
    if (!mediaEl) return;
    mediaEl.currentTime = ms / 1000;
    mediaEl.play();
  }

  function onTimeUpdate() {
    if (mediaEl) currentMs = mediaEl.currentTime * 1000;
  }

  async function copyMarkdown() {
    const resp = await fetch(downloadUrl);
    if (!resp.ok) return;
    const text = await resp.text();
    await navigator.clipboard.writeText(text);
    copyState = 'copied';
    setTimeout(() => { copyState = 'idle'; }, 2000);
  }

  function sendEmail() {
    if (!emailTo.trim()) return;
    localStorage.setItem('review-email', emailTo.trim());
    const sub = encodeURIComponent(`Interview Review — ${report.source_filename}`);
    const body = encodeURIComponent(
      `Hi,\n\nHere is a link to my interview review:\nhttp://localhost:3000/review/${report.id}\n\nReport ID: ${report.id}\n\nGenerated by AI Interview Assist.`
    );
    window.open(`mailto:${encodeURIComponent(emailTo.trim())}?subject=${sub}&body=${body}`.slice(0, 2000), '_self');
    emailSent = true;
    setTimeout(() => { emailSent = false; }, 3000);
  }

  async function doDelete() {
    const resp = await fetch(`/api/review/${report.id}`, { method: 'DELETE' });
    if (resp.ok) onDelete?.(report.id);
    onClose();
  }
</script>

<div class="modal-backdrop" onclick={onClose} role="none">
  <div class="modal" onclick={(e) => e.stopPropagation()} role="dialog">

    <!-- Header -->
    <div class="modal-header">
      <div class="header-left">
        <h2>{report.source_filename || 'Interview Review'}</h2>
        <span class="meta">
          {fmtDate(report.created_at)} · {fmtDuration(report.duration_secs)}
          {#if report.source_type === 'live'}
            <span class="badge live">Live</span>
          {:else}
            <span class="badge upload">Upload</span>
          {/if}
        </span>
      </div>
      <button class="close-btn" onclick={onClose}>✕</button>
    </div>

    <div class="modal-body">

      <!-- Summary row -->
      <div class="summary-row">
        <div class="stat-card">
          <span class="stat-val">{report.speaker_summary.you_pct.toFixed(0)}%</span>
          <span class="stat-label">You spoke</span>
        </div>
        <div class="stat-card">
          <span class="stat-val">{report.vocal_summary.avg_wpm}</span>
          <span class="stat-label">avg WPM</span>
        </div>
        <div class="stat-card">
          <span class="stat-val">{report.qa_pairs.length}</span>
          <span class="stat-label">Q&amp;A pairs</span>
        </div>
        <div class="stat-card">
          <span class="stat-val">{report.keywords_mentioned.length}</span>
          <span class="stat-label">keywords used</span>
        </div>
      </div>

      {#if report.keywords_mentioned.length > 0}
        <div class="keyword-row">
          {#each report.keywords_mentioned as kw}
            <span class="kw-chip">{kw}</span>
          {/each}
        </div>
      {/if}

      <!-- Replay -->
      <div class="replay-section">
        <div class="section-label">REPLAY</div>
        {#if isVideo}
          <!-- svelte-ignore a11y_media_has_caption -->
          <video
            bind:this={mediaEl}
            src={sourceUrl}
            controls
            class="media-el"
            ontimeupdate={onTimeUpdate}
          ></video>
        {:else}
          <audio
            bind:this={mediaEl}
            src={sourceUrl}
            controls
            class="audio-el"
            ontimeupdate={onTimeUpdate}
          ></audio>
        {/if}

        <!-- Transcript sync -->
        <div class="transcript-scroll">
          {#each report.transcript as seg, i}
            <div
              class="seg"
              class:active={activeSegIdx() === i}
              class:you={seg.speaker === 'You'}
              role="button"
              tabindex="0"
              onclick={() => seekTo(seg.start_ms)}
              onkeydown={(e) => { if (e.key === 'Enter') seekTo(seg.start_ms); }}
            >
              <span class="seg-speaker">{seg.speaker}</span>
              <span class="seg-time">{fmtDuration(seg.start_ms / 1000)}</span>
              <span class="seg-text">{seg.text}</span>
            </div>
          {/each}
        </div>
      </div>

      <!-- Q&A -->
      {#if report.qa_pairs.length > 0}
        <div class="section-label">Q&amp;A COACHING</div>
        {#if currentMs === 0 && report.qa_pairs.length > 0}
          <div class="qa-replay-hint">▶ Play recording to reveal coaching cards in real time</div>
        {/if}
        <div class="qa-list" bind:this={qaListEl}>
          {#each visibleQa as qa, i}
            {@const open = expandedQa === i}
            <div class="qa-item">
              <button class="qa-header" onclick={() => { expandedQa = open ? null : i; }}>
                <span class="qa-q">{qa.question}</span>
                <div class="qa-badges">
                  {#if qa.missed_followup}
                    <span class="badge miss">no follow-up</span>
                  {/if}
                  {#if qa.missed_metric}
                    <span class="badge miss">no metric</span>
                  {/if}
                  <span class="badge wpm" style="color:{wpmColor(qa.wpm)}">{qa.wpm} wpm · {fmtWpm(qa.wpm)}</span>
                  <span role="button" tabindex="0" class="seek-btn" title="Jump to question" onclick={(e) => { e.stopPropagation(); seekTo(qa.start_ms); }} onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.stopPropagation(); seekTo(qa.start_ms); } }}>⏩ {fmtDuration(qa.start_ms / 1000)}</span>
                  <span class="chevron">{open ? '▾' : '▸'}</span>
                </div>
              </button>
              {#if open}
                <div class="qa-body">
                  <div class="qa-answer-label">Your answer ({fmtDuration(qa.duration_secs)})</div>
                  <p class="qa-answer">{qa.answer_text}</p>
                  <div class="qa-coaching-label">Coaching</div>
                  <p class="qa-coaching">{qa.coaching}</p>
                </div>
              {/if}
            </div>
          {/each}
        </div>
      {/if}

    </div><!-- end modal-body -->

    <!-- Share footer -->
    <div class="share-footer">
      <a class="share-btn" href={downloadUrl} download>↓ Download .md</a>
      <button class="share-btn" class:copied={copyState === 'copied'} onclick={copyMarkdown}>
        {copyState === 'copied' ? '✓ Copied!' : 'Copy report'}
      </button>
      <div class="email-row">
        <input
          class="email-input"
          type="email"
          placeholder="Email report…"
          bind:value={emailTo}
          onkeydown={(e) => { if (e.key === 'Enter') sendEmail(); }}
        />
        <button class="send-btn" class:sent={emailSent} onclick={sendEmail} disabled={!emailTo.trim()}>
          {emailSent ? '✓' : '✉'}
        </button>
      </div>
      {#if onDelete}
        {#if confirmDelete}
          <button class="del-confirm-btn" onclick={doDelete}>Confirm delete</button>
          <button class="del-cancel-btn" onclick={() => { confirmDelete = false; }}>Cancel</button>
        {:else}
          <button class="del-btn" onclick={() => { confirmDelete = true; }}>Delete</button>
        {/if}
      {/if}
    </div>

  </div>
</div>

<style>
  .modal-backdrop {
    position: fixed; inset: 0; background: rgba(0,0,0,0.75);
    display: flex; align-items: center; justify-content: center;
    z-index: 200;
  }
  .modal {
    background: #0f172a; border: 1px solid #1e293b; border-radius: 0.75rem;
    width: min(760px, 97vw); max-height: 90vh;
    display: flex; flex-direction: column; overflow: hidden;
  }
  .modal-header {
    display: flex; align-items: flex-start; justify-content: space-between;
    padding: 1rem 1.5rem; border-bottom: 1px solid #1e293b; flex-shrink: 0; gap: 1rem;
  }
  .header-left { display: flex; flex-direction: column; gap: 0.25rem; min-width: 0; }
  h2 { font-size: 1rem; font-weight: 700; color: #f1f5f9; margin: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .meta { font-size: 0.78rem; color: #64748b; display: flex; align-items: center; gap: 0.4rem; flex-wrap: wrap; }
  .close-btn {
    background: none; border: none; color: #64748b; font-size: 1rem;
    cursor: pointer; flex-shrink: 0; padding: 0.2rem 0.4rem;
  }
  .close-btn:hover { color: #e2e8f0; }

  .modal-body {
    overflow-y: auto; padding: 1.25rem 1.5rem;
    display: flex; flex-direction: column; gap: 1.25rem; flex: 1;
  }

  /* Summary */
  .summary-row {
    display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem;
  }
  .stat-card {
    background: #0a1628; border: 1px solid #1e293b; border-radius: 0.5rem;
    padding: 0.75rem; display: flex; flex-direction: column; align-items: center; gap: 0.2rem;
  }
  .stat-val { font-size: 1.4rem; font-weight: 700; color: #60a5fa; }
  .stat-label { font-size: 0.72rem; color: #64748b; text-align: center; }

  .keyword-row { display: flex; flex-wrap: wrap; gap: 0.35rem; }
  .kw-chip {
    padding: 0.15rem 0.6rem; border-radius: 1rem;
    background: rgba(59,130,246,0.12); border: 1px solid rgba(59,130,246,0.3);
    color: #93c5fd; font-size: 0.75rem;
  }

  /* Badges */
  .badge { font-size: 0.68rem; padding: 0.1rem 0.45rem; border-radius: 0.25rem; font-weight: 600; letter-spacing: 0.03em; }
  .badge.live { background: rgba(167,139,250,0.15); color: #a78bfa; }
  .badge.upload { background: rgba(59,130,246,0.12); color: #60a5fa; }
  .badge.miss { background: rgba(248,113,113,0.12); color: #f87171; }
  .badge.wpm { background: transparent; font-size: 0.72rem; }

  /* Replay */
  .section-label {
    font-size: 0.68rem; font-weight: 700; letter-spacing: 0.1em;
    color: #475569; text-transform: uppercase; margin-bottom: -0.5rem;
  }
  .replay-section { display: flex; flex-direction: column; gap: 0.75rem; }
  .media-el { width: 100%; border-radius: 0.5rem; background: #000; max-height: 240px; object-fit: contain; }
  .audio-el { width: 100%; }

  .transcript-scroll {
    max-height: 180px; overflow-y: auto;
    border: 1px solid #1e293b; border-radius: 0.5rem;
    display: flex; flex-direction: column;
  }
  .seg {
    display: flex; align-items: baseline; gap: 0.5rem;
    padding: 0.35rem 0.75rem; cursor: pointer; transition: background 0.1s;
    font-size: 0.8rem;
  }
  .seg:hover { background: #0f1f35; }
  .seg.active { background: rgba(59,130,246,0.12); }
  .seg-speaker { color: #64748b; min-width: 5rem; font-size: 0.72rem; text-transform: uppercase; flex-shrink: 0; }
  .seg.you .seg-speaker { color: #60a5fa; }
  .seg-time { color: #334155; min-width: 2.5rem; font-size: 0.72rem; flex-shrink: 0; }
  .seg-text { color: #94a3b8; line-height: 1.4; flex: 1; }

  /* Q&A */
  .qa-replay-hint {
    font-size: 0.78rem; color: #475569; text-align: center;
    padding: 0.6rem; background: #060e1a; border: 1px dashed #1e293b;
    border-radius: 0.5rem;
  }
  .qa-list { display: flex; flex-direction: column; gap: 0.5rem; }
  .seek-btn {
    background: transparent; border: 1px solid #1e3a5f; border-radius: 0.25rem;
    color: #60a5fa; font-size: 0.68rem; padding: 0.1rem 0.4rem;
    cursor: pointer; flex-shrink: 0; white-space: nowrap;
    transition: background 0.15s;
  }
  .seek-btn:hover { background: rgba(59,130,246,0.12); }
  .qa-item { border: 1px solid #1e293b; border-radius: 0.5rem; overflow: hidden; }
  .qa-header {
    width: 100%; display: flex; align-items: flex-start; justify-content: space-between;
    gap: 0.75rem; padding: 0.65rem 0.75rem; background: #0a1628;
    border: none; cursor: pointer; text-align: left;
  }
  .qa-header:hover { background: #0f1f35; }
  .qa-q { color: #cbd5e1; font-size: 0.85rem; flex: 1; line-height: 1.4; }
  .qa-badges { display: flex; align-items: center; gap: 0.35rem; flex-shrink: 0; flex-wrap: wrap; justify-content: flex-end; }
  .chevron { color: #475569; font-size: 0.75rem; flex-shrink: 0; }
  .qa-body { padding: 0.75rem; background: #060e1a; display: flex; flex-direction: column; gap: 0.5rem; }
  .qa-answer-label, .qa-coaching-label { font-size: 0.68rem; font-weight: 700; letter-spacing: 0.08em; color: #475569; text-transform: uppercase; }
  .qa-answer { color: #94a3b8; font-size: 0.83rem; line-height: 1.5; margin: 0; }
  .qa-coaching { color: #7dd3fc; font-size: 0.83rem; line-height: 1.5; margin: 0; }

  /* Share footer */
  .share-footer {
    display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap;
    padding: 0.75rem 1.5rem; border-top: 1px solid #1e293b;
    background: #080f1c; flex-shrink: 0; border-radius: 0 0 0.75rem 0.75rem;
  }
  .share-btn {
    padding: 0.3rem 0.7rem; background: transparent;
    border: 1px solid #334155; border-radius: 0.3rem;
    color: #64748b; font-size: 0.8rem; cursor: pointer; text-decoration: none;
    transition: all 0.15s; display: inline-flex; align-items: center;
  }
  .share-btn:hover { border-color: #60a5fa; color: #60a5fa; }
  .share-btn.copied { border-color: #4ade80; color: #4ade80; }
  .email-row { display: flex; align-items: center; gap: 0.35rem; flex: 1; min-width: 180px; }
  .email-input {
    flex: 1; padding: 0.28rem 0.6rem; background: #0f172a; border: 1px solid #1e293b;
    border-radius: 0.3rem; color: #e2e8f0; font-size: 0.8rem; outline: none;
    transition: border-color 0.15s;
  }
  .email-input:focus { border-color: #3b82f6; }
  .send-btn {
    padding: 0.28rem 0.6rem; background: #1d4ed8; border: none; border-radius: 0.3rem;
    color: white; font-size: 0.85rem; cursor: pointer; transition: background 0.15s;
  }
  .send-btn:hover:not(:disabled) { background: #2563eb; }
  .send-btn:disabled { opacity: 0.4; cursor: default; }
  .send-btn.sent { background: #166534; }
  .del-btn {
    margin-left: auto; padding: 0.28rem 0.6rem; background: transparent;
    border: 1px solid #450a0a; border-radius: 0.3rem; color: #7f1d1d;
    font-size: 0.8rem; cursor: pointer; transition: all 0.15s;
  }
  .del-btn:hover { border-color: #f87171; color: #f87171; }
  .del-confirm-btn {
    margin-left: auto; padding: 0.28rem 0.6rem; background: #7f1d1d;
    border: none; border-radius: 0.3rem; color: #fca5a5; font-size: 0.8rem; cursor: pointer;
  }
  .del-cancel-btn {
    padding: 0.28rem 0.6rem; background: none; border: 1px solid #334155;
    border-radius: 0.3rem; color: #64748b; font-size: 0.8rem; cursor: pointer;
  }
</style>
